dbt_project:
  outputs:
    dev:
      account: ********.switzerland-north.azure
      database: AIRBNB_DB
      password: *********
      role: ROLE_PRO
      schema: MAIN
      threads: 4
      type: snowflake
      user: *******
      warehouse: DBTDW

  target: devs
